services:
  mysql:
    image: mysql/mysql-server:8.0.27
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gooty
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql:
    driver: local
